# Python basico para scripts breves

## Nota
Python es un lenguaje relativamente antiguo y, en los ultimos anios (o, en las ultimas decadas) ha cambiado bastante. Originalmente, su lema era "una sola forma, y obvia, de hacer cada cosa" (traduccion libre de "_there is only one obvius way to do it_"). En el Python actual, ese lema parece una broma cruel. Hay varias maneras de crear una lista, leer un archivo, etc. Incluso hay dos maneras de formatear texto! 

En mi caso, empece a usar Python entre 2005-2006. El Python que enseno, es basicamente el que uso desde ese entonces (claro que, adaptado a Python 3). No soy partidario de agregar cosas redundantes a un lenguaje, y, por tanto, preferi cenirme a lo que ya existia. Por esta razon, en esta guia no se ensena la forma "RAII" de leer archivos (**with**) ni la forma "recomendada" de formatear texto.

Por otra parte, esta guia esta pensada para Python como lenguaje de _scripting_, para automatizar trabajos breves, no para escribir programas largos. Eso es todo lo que necesita la gran mayoria de los usuarios del area de las Ciencias Naturales y, en mi opinion, Python no es un lenguaje apropiado para programas complejos, de todos modos. Por esto, no se incluyen temas como programacion orientada a objetos.

---




Un programa es basicamente un conjunto de instrucciones, una despues de otra, que el computador "ejecuta" en orden.
Esas instrucciones normalmente incluyen manipular valores (numeros o textos) guardados en la memoria. Esos valores se guardan en variables


In [ ]:
#una parte importante de un programa son los comentarios
#todo lo que venga despues de '#' es un comentario, y es completamente
#ignorado por el computador. Existe solamente para ayudarnos a entender
#el programa

En linux, todo programa en python comienza con lo siguiente:

In [ ]:
#!/usr/bin/env pyhton

Esto no es realmente parte del programa. Es para que el sistema operativo sepa que este archivo contiene un programa escrito en Pythong.


## la funcion print

Esta funcion nos muestra algo en la pantalla. Si queremos que nos muestre texto, tenemos que ponerlo entre comillas. Fijense que cada llamado a **print** imprime texto en una linea separada. Es decir, **print** agrega un _salto de linea_ a todo lo que imprime.

In [ ]:
print("Hola, mundo!")

print("Estimadas")
print("y estimados")

## variables

Una variable es un nombre que lleva asociado un valor

In [ ]:
a = 2 # a es una variable que contiene el valor 2

print(a)

#en general, voy a usar a, b, c, d, etc. como nombres de variables, pero una variable puede
#tener casi cualquier nombre!

numero = 4.5  #numero es una variable que contiene el valor 4.5

EJEMPLO = 10 #los nombrmes de variables pueden ser casi cualquier, con tal de que parta con una letra
#y que no tenga "simbolos"

ejemplo2 = 6 #los nombres de variables pueden contener numeros, pero no pueden empezar con numeros



In [7]:
%variableerronea = 5 #esto va a dar error, la variable no puede contener simbolos

UsageError: Line magic function `%variableerronea` not found.


In [8]:
4you = 56 #esto tambien va a dar error, la variable no puede partir con numero

SyntaxError: invalid decimal literal (<ipython-input-8-a9879bd728cb>, line 1)

In [11]:
for = 8 #finalmente, hay palabras "reservadas" que son parte del lenguaje Python, y no se pueden usar 
#como nombres de variables. "for" es una palabra reservada, asi es que esto va a dar error (mas adelante 
#vamos a ver que significa "for" en el lenguaje!)

SyntaxError: invalid syntax (<ipython-input-11-195c871db242>, line 1)

Hay varios tipos de variable:

### Variables 'simples'

#### Variables numericas

Almacenan valores numericos. Hay dos tipos: int y float. Int contiene numeros enteros, float, contiene numeros con parte decimal




In [1]:
a = 2 #int

b = 14.5 #float

c = a + b  #Si una operacion combina int y float, a es implicitamente transformado a float y c va a ser float

print(c)



17.5


Python soporta varias "operaciones" entre variables numericas. Basicamente, todas las operaciones aritmeticas como suma (+) multiplicacion (\*), division (/), y otras. La _precedencia_ de los operadores es la que uno espera (multiplicacion tiene mas precedencia que suma, etc). Cuando tenemos dudas acerca de la precedencia de operadores, podemos usar parentesis para asegurarnos y hacer nuestro codigo mas claro


In [5]:
a = 3
b = 4
c = 10.5

print("suma", a+b)
print("resta", a-b)
print("multiplicacion", a*b)
print("potencia", a**b) #a elevado a b
print("division", c/a) #esta division convierte el resultado en "float" si es necesario
print("division entera", c//a) #division entera, simplemente desprecia la parte decimal del resultado
print("resto", b%a) #resto de la division entre a y b
print("Operacion combinada", a*c-c/b+a) # notese la precedencia 
#de * y / sobre + y -


suma 7
resta -1
multiplicacion 12
potencia 81
division 3.5
division entera 3.0
resto 1
Operacion combinada 31.875


Podemos asignar el resultado de una operacion a otra variable

In [6]:
a = 15
b = 3
c = a - b
print(c)
c = a/b -c #notese que aca la variable c aparece a los dos lados de la asignacion!
print(c)
#aca vemos otro ejemplo de como una variable puede participar en una expresion
#que se asigna a esa misma variable.
d = 1
print(d)
d = d +1
print(d)

12
-7.0
1
2


Los simbolos que usamos para cada operacion (como -, +, \*) se denominan _operadores_

#### Variables de tipo texto

Estas variables no contienen numeros, sino, bueno, texto :-) las variables de tipo texto son cualquier cadena de texto delimitada por comillas


In [12]:
a = "Hola" #a es una variable de tipo texto

print(a) #podemos imprimirla en pantalla igual que un numero

b = " amigos!"

c = a+b # si usamos el operador suma (+) sobre dos variables de texto, las va a concatenar
print(a+b) 




Hola
Hola amigos!


In [13]:
texto = "hola!"
numero =1

print(texto+numero) #si tratamos de mezclar texto con numero en una operacion, se va a producir un error

TypeError: can only concatenate str (not "int") to str

Las variables de texto son mas "complejas" que las variables numericas, en el sentido de que se puede acceder a una parte de ellas. 

In [15]:
a = "Hola amigos!"

print(a[0]) # a[0] es la primera letra de la variable a.
print(a[6]) #a[6] es la septima letra (cada espacio en blanco cuenta como una letra)

#notese que los indices parten de 0: el primera valor es a[0], el segundo es a[1], etc.



h
m


Tambien podemos acceder a una letra o caracter de una cadena de texto desde atras hacia adelante.
**a[-1]** representa el ultimo caracter de **a**, **a[-2]** el penultimo, etc.



In [ ]:
ejemplo = "Hola a todo el mundo!"

print(ejemplo[-1])
print(ejemplo[-3])


Finalmente, podemos acceder no solamente a una letra o caracter de la cadena de texto, sino a una sub-cadena
con varios caracteres


In [1]:
ejemplo = "Hola a todo el mundo!"

b = ejemplo[1:7] #los caracteres entre b[1] y b[7], sin incluir a este ultimo. 
#Recueden que b[1] es el segundo caracter\

print(b) #b contiene la sub-cadena "ola a", que es una cadena de texto por si misma.

ola a 


Un caracter especial es "\\n" que simboliza un salto de linea

In [4]:
var = "Dos lineas\nde texto"
print(var)

Dos lineas
de texto


#### Variables booleanas

Otro tipo de variables son las variables _booleanas_. Estas son variables especiales que solamente pueden contener dos valores: **True** (verdadero) o **False** (falso). 

Estas variables soportan tres operadores especiales, que solamente funcionan con variables booleanes. Estos operadores son:

- and
- or
- not

In [2]:
var = True
var2 = False  #var y var2 son variables booleanas
print(var,var2)

var3 = var and var2 #esta operacion da como resultado True solamente si var y var2 son True
print(var3)
var3 = var or var2 #esta operacion da resultado True si var o var2 son True
print(var3)
var3 = not var2 #esta operacion da como resultado True si var2 es False, y False si var2 es True


True False
False
True


Existen operaciones que "operan" sobre variables _no_ booleanas (numericas, de texto, etc) pero que entregan resultados que si son booleanos. Estas son las operaciones de _comparacion_, que nos permiten comparar dos variables:

- \> (mayor que)
- \< (menor que)
- \>= (mayor o igual que)
- \<= (menor o igual que)
- == (igual a)
- != (no igual a)


In [8]:
a=1
b=2
d = 3
c="Hola"
d = "Chao"


print(a==b) #False, a y b no son iguales
print(d == (a+b)) #verdadero (True)
print(a>=b) #False, a no es mayor o igual que b
print(c==d) #False, ambas cadenas no son iguales
print(c>d) #Esto se puede hacer, y de True, porque c comienza con una letra "mayor" en el abecedario que d
#pero, en general, recomiendo no usar >,<,>=,<= con text y limitarse a preguntar si son iguales.

print(c[1]==d[-1]) #True (verdadero), tanto c[1] como d[-1] contienen el mismo caracter, "o"

print("HOLA"==c) #esto es False (falso) porque c contiene "Hola" que no es igual a "HOLA".
#Python distingue entre letras mayusculas y minusculas.

False
False
False
False
True


Las variables que hemos visto hasta ahora tienen algo en comun. Son *inmutables*. Eso significa que, una vez 
que se les asigna un valor, este no puede cambiar.

In [ ]:
var = 1 #ya no es posible asignar otro valor a la variable var

var =2 #entonces como esto funciona sin errores?

print(var) 

La respuesta es que lo que hacemos en la linea 3 del ejemplo anterior no es realmente asignar otro valor a la variable **var**. Lo que ocurre en la linea 3 es que la variable **var** que habiamos definido en la linea 1 es destruida, y se crea _otra_ variable con el mismo nombre, pero con otro valor, y que reside en una direccion diferente en la memoria.

El hecho de que estas variables efectivamente no se pueden cambiar, podemos comprobarlo si tratamos de cambiar _una parte_ de una variable de texto.

In [1]:
var = "Hola amigas!"

var[-3]="o" #tratamos de cambiar "Hola amigas!" por "Hola amigos!", pero esto va a dar 
#un error, porque las cadenas de texto son inmutables.

TypeError: 'str' object does not support item assignment

Lo unico que podemos hacer es reemplazar la cadena de texto original por otra variable con el mismo nombre, pero no podemos alterar la variable en si.


In [ ]:
var = "Hola amigos!"
print(var)
var = "Hola amigas y amigos!" #esto no da error, porque no cambiamos la variable
#si no que la reemplazamos por otra con el mismo nombre
print(var)


### Conversiones de tipos

En muchos casos, se quiere convertir una variable en otra, de otro tipo. Por ejemplo, la variable "2" no es el numero 2, sino que es una cadena de texto que dice 2 Si queremos usarla como numero, tenemos que convertirla


In [15]:
tvar="2" # variable de texto
tvar2="3" #texto
print(tvar+tvar2) #esto no da 5, sino "23", puesto que tvar y tvar2 son cadenas de caracter,
#al "sumarlas" Python las concatena.

var=int(tvar)  #asi convertimos una variable en un numero entero.
var2=int(tvar2)
print(var+var2) #ahora si la suma da 5



23
5


In [18]:
tvar= "2.2" #esto no es un numero, es un texto
print(tvar*2) #esto no multiplica 2.2 por dos, sino que duplica la cadena de texto

fvar=float(tvar) #transformamos el texto en un "float" y se lo asignamos a fvar

print(fvar*2) #ahora si obtenemos el resultado esperado

2.22.2
4.4


In [20]:
tvar="2.2"

intvar = int(tvar) #Error! el texto "2.2" no puede convertirse en un numero entero, solo en un float

ValueError: invalid literal for int() with base 10: '2.2'

In [19]:
tvar="hola!"

intvar=int(tvar) #otro error! el texto "hola!" no se puede convertir en numero

ValueError: invalid literal for int() with base 10: 'hola!'

### Colecciones

Las colecciones son variables que representan "conjuntos" de otras variables. Vamos a ver algunas que se usan con frecuencia.

#### Listas

Tal vez la coleccion mas usada. Una lista es una coleccion de variables que se ubican en orden, de modo tal que podemos acceder a cada variable si conocemos su orden en la lista.

Para crear una lista, simplemente ponemos las variables que queremos que formen parte de esta en el orden deseado, separadas por comas, y rodeadas de corchetes ("**\[**" y "**\]**")


In [7]:
listita = [1,2,3,4,5,6,7] #"la variable "listita" es una lista

print(listita) #imprimimos toda la lista

print(listita[2]) # podemos acceder a un elemento de la lista si conocemos su posicion. 
#esto funciona igual que en las cadenas de texto. Los indices tambien parten desde 0
#por lo que listita[2] es el tercer elemento de la lista.

print(listita[-2]) #Tambien podemos usar indices "inversos" como en cadenas de text

print(listita[2:5]) #exactamente igual que con el texto, eso nos da una sub-lista
#con los elementos del 2 al 5 (excluyendo este ultimo). Esta sub-lista es tambien
#una lista por si misma.


[1, 2, 3, 4, 5, 6, 7]
3
6
[3, 4, 5]


A diferencia de las variables que hemos visto hasta ahora, las listas pueden modificarse. Se dice que son "mutables".

In [1]:
listita = [1,2,3,4,5,6,7] 

listita[2]=20 #esto seria un error en una cadena de texto, pero es correcto en una lista.


print(listita)

listita[3]="hola!"

print(listita)

listita[1]=[10,11,12] #cada elemento de una lista puede ser cualquier cosa, incluyendo otra lista.

print(listita)

[1, 2, 20, 4, 5, 6, 7]
[1, 2, 20, 'hola!', 5, 6, 7]
[1, [10, 11, 12], 20, 'hola!', 5, 6, 7]


Si tenemos una lista de listas como

```
a=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
```

y queremos acceder al elemento segundo elemento (indice 1) de la tercera lista (indice 2) usamos:

In [8]:
a=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

print(a[2][1])

a[0][2]=30 #tambien podemos usar esta sintaxis para modificar elementos de una lista de listas

print(a)

print(a[1][1:3]) #podemos usar tambien esta sintaxis para obtener una sub-lista de una de nuestras listas.

10
[[1, 2, 30, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[6, 7]


#### Tuplas

Son similares a las listas, pero son inmutables. Para definir una tupla, basta poner los elemento separados por comas, aunque suelen encerrarse entre parentesis, por claridad.

In [3]:
tup=(1,2,"hola!",3,[4,5,6]) #el ultimo elemento de esta tupla es una lista.

print(tup)

tup2=3,4,5 #tambien se pueden definir sin parentesis, aunque es preferible usarlos

print(tup2)

(1, 2, 'hola!', 3, [4, 5, 6])
(3, 4, 5)


In [4]:
tup=(1,2,3,4)

tup[1]=10 #Error! Las tuplas son inmutables, no se pueden modificar


TypeError: 'tuple' object does not support item assignment

In [5]:
tup=(1,2,"hola!",3,[4,5,6])

tup[-1][1]=10 #esto si es correcto, porque no estamos modificando la tupla, estamos modificando la lista
#que va dentro de la tupla.

print(tup)

(1, 2, 'hola!', 3, [4, 10, 6])


#### Diccionarios

Similares a las listas, y tambien mutables, pero los elementos _no_ tienen un orden establecido. En lugar de eso, cada elemento o "valor" (_value_) del diccionario tiene asociada una "clave" (_key_) que se usa para acceder a el.

Nota: En las ultimas versiones de Python, los diccionarios muchas veces **si** tienen un orden establecido, pero prefiero ensenar a no depender de eso.

Para crear un diccionario, se entregan pares clave/valor separados entre si por dos puntos ":", cada par separado del siguiente por una come "," y todo rodeado por llavas "{}"

In [10]:
d={"nombre":"Clara","email":"clara@empresa.cl","telefono":58909222} #Creamos un diccionario

print(d)

e=d["email"]
print(e)

d["nombre"]="Clara A." #Podemos modificar un valor cualquiera del diccionario
print(d)

d["ciudad"]="Santiago" #Tambien podemos agregar elementos nuevos
print(d)

{'nombre': 'Clara', 'email': 'clara@empresa.cl', 'telefono': 58909222}
clara@empresa.cl
{'nombre': 'Clara A.', 'email': 'clara@empresa.cl', 'telefono': 58909222}
{'nombre': 'Clara A.', 'email': 'clara@empresa.cl', 'telefono': 58909222, 'ciudad': 'Santiago'}


## Control de flujo

Hasta ahora, todos nuestros programas ejecutan siempre las mismas instrucciones. En realidad, necesitamos que un programa sea capaz que cambiar las instrucciones que ejecuta, dependiendo de los datos que este procesando.

Una forma de hacer esto es el constructo **if**. Este constructo ejecuta algo solamente si una operacion da como resultado el valor _booleano_ **True**

In [13]:
a=10 #el valor de a podria ser leido de un archivo, o venir del usuario

if a>20:
    print("esto solo se imprime si a es mayor que 20")
    print("esto tambien")
print("esto se imprime siempre")

if a>0:
    print("esto solamente se imprime si a es positivo")
    print("esto tambien!")
    b=a+20
    print("y esto!",b)
print("esto se imprime siempre")

esto se imprime siempre
esto solamente se imprime si a es positivo
esto tambien!
y esto! 30
esto se imprime siempre


Nota que despues del **if** viene una serie de instrucciones que solamente se ejecutan si el argumento de **if** da como resultado **True**. Esas instrucciones que estan "bajo la influencia" del **if** forman un _bloque_. En Python, los bloques se delimitan con sangrias (identaciones) (esto es una muy mala idea por varias razones, pero eso asi). Cuando se acaban las sangrias, los elementos dejan de formar parte del _bloque_, y ya no dependen den **if** sino que se ejecutan siempre.

Ahora tenemos una forma de ejecutar codigo solamente si una condicion se cumple, y, despues seguir ejecutando codigo tanto si una condicion se cumple, como si no.

Pero que pasa si queremos ejecutar un conjunto de instrucciones si la condicion se cumple, y otro conjunto distinto si la condicion _no_ se cumple? para esto existe el constructo **else**

In [14]:
a=10 #el valor de a podria ser leido de un archivo, o venir del usuario
b=20

if a>b:
    print("esto solo se imprime si a es mayor que b")
    print("esto tambien")
else:
    print("esto solamente se imprime si a NO es mayor que b")
    print("esto tambien, solo si a NO es mayor que b")
print("esto se imprime siempre")

esto solamente se imprime si a NO es mayor que b
esto tambien, solo si a NO es mayor que b
esto se imprime siempre


### El _bucle_ **for**

En varios casos, necesitamos repetir el mismo set de instrucciones varias veces, pero el numero exacto de veces no es conocido, sino que depende del usuario. Por ejemplo, digamos que queremos calcular el promedio de una lista de numeros. Tenemos que sumar todos los numeros de la lista, y dividirlos entre el total de numeros.
Si la lista nos la entrega el usuario, no tenemos manera de saber cuantas veces tenemos que sumar. Para esto sirve el bucle **for**.

**for** repite el numero de instrucciones en su _bloque_ tantas veces como elementos tenga una lista, asignando cada vez un elemento de la lista a una variable. Veamoslo con un ejemplo


In [21]:
milista=[1,3,5,7]

suma=0
elementos_totales=0
for i in milista:
    #todo lo que esta en ese bloque se ejecuta tantas veces somo elementos haya en "milista".
    #en cada "iteracion", se le asigna un nuevo elemento de la lista a la variable i
    print("estamos procesando el elemento", i)
    suma=suma+i
    elementos_totales=elementos_totales+1

#termino el "bloque" de for. Todo lo que viene se ejecuta una sola vez.
promedio=suma/elementos_totales

print("El promedio es", promedio)
    

estamos procesando el elemento 1
estamos procesando el elemento 3
estamos procesando el elemento 5
estamos procesando el elemento 7
El promedio es 4.0


In [22]:
milista=[1,3,5,7,"texto1",11,13,"texto2"]

for var in milista:
    print(var) #en la primera "vuelta" o "ronda" var vale 1, despues 3, etc.
print("Esto solamente se ejecuta cuando terminamos de iterar por la lista")


1
3
5
7
texto1
11
13
texto2
Esto solamente se ejecuta cuando terminamos de iterar por la lista


Hay veces que no solamente queremos conocer, en cada ronda de iteracion, el valor del elemento de la lista que corresponde a esa ronda, sino, tambien, el _numero_ de la ronda en si. Por ejemplo, podemos querer saber si el elemento que estamos procesando es el primer, segundo, tercer, o cuarto elemento de la lista. Para esto nos sirve la funcion **enumerate**

In [23]:
milista=[1,3,5,7,"texto1",11,13,"texto2"]

for indice,valor in enumerate(milista):
    print("El elemento de la lista con indice", indice, "vale", valor) 
print("Esto solamente se ejecuta cuando terminamos de iterar por la lista")

El elemento de la lista con indice 0 vale 1
El elemento de la lista con indice 1 vale 3
El elemento de la lista con indice 2 vale 5
El elemento de la lista con indice 3 vale 7
El elemento de la lista con indice 4 vale texto1
El elemento de la lista con indice 5 vale 11
El elemento de la lista con indice 6 vale 13
El elemento de la lista con indice 7 vale texto2
Esto solamente se ejecuta cuando terminamos de iterar por la lista


Finalmente, hay veces que queremos ejecutar un conjunto de instrucciones un numero (tal vez desconocido) 
de veces pero no queremos procesar ninguna lista. En ese caso nos ayuda la funcion **range**. Range genera algo parecido a una lista (no nos vamos a meter en detalles), que podemos usar para iterar. 

In [24]:
a=10 #digamos que queremos ejecutar un conjunto de instrucciones "a" veces.

for i in range(a):
    print("ejecutando la iteracion", i)

#Tambien podemos usar range para generar listas (tenemos que convertir el resultado en una lista)

b=list(range(a)) #con list() convertimos lo que produce "range" en una lista

print(b)
c=2
b=list(range(c,a)) # Esto nos da una lista que va entre c y a (sin incluir este ultimo)
print(b)

e=3
b=list(range(c,a,e)) #esto nos da una lista que va entre c y a, saltandose  e pasos cada vez
print(b)

ejecutando la iteracion 0
ejecutando la iteracion 1
ejecutando la iteracion 2
ejecutando la iteracion 3
ejecutando la iteracion 4
ejecutando la iteracion 5
ejecutando la iteracion 6
ejecutando la iteracion 7
ejecutando la iteracion 8
ejecutando la iteracion 9
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4, 5, 6, 7, 8, 9]
[2, 5, 8]


####  **break** y **continue**

Hay varias razones por las que podriamos querer detener las iteraciones en un bucle **for**, o saltarnos algunas. Para eso nos sirven **break** y **continue**

**break** detiene las iteraciones en un bucle. Por ejemplo digamos que tenemos una lista desconocida, y queremos contar sumar los elementos, pero queremos detener la cuenta si resulta ser mayor que un numero:


In [25]:
lista=[1,3,6,50,20,55,60,2,6]

suma=0 #esta variable va a ir guardando la suma de los elementos de la lista
for i in lista:
    suma=suma+i
    if suma>=100:
        break
        
print("Esta no es la suma total, sino que se detiene al llegar a 100. Valor final:", suma)
    

Esta no es la suma total, sino que se detiene al llegar a 100 135


Ahora consideremos un caso en el que queremos sumar solamente los elementos de una lista que sean numeros _pares_. Podemos usar **continue**. Continue es similar a **break** pero no termina las iteraciones. Simplemente termina la iteracion actual, y comienza con la siguiente

In [27]:
lista=[1,2,3,4,5,6,7,8,9] 

suma=0

for i in lista:
    if i%2!=0:  #recuerda que i%2 es el resto de la division entre i y 2. != significa "no igual a"
        continue #si encontramos un numero impar, nos lo saltamos.
    suma=suma+i
print(suma)

20


## Funciones

Las funciones son bloques de codigo que podemos "llamar" varias veces. Algunas funciones "devuelven" un resultado, como las funciones matematicas. Algunas funciones reciben "argumentos", tambien como las funciones matematicas. Algunas funciones no devuelven ningun resultado, y algunas no reciben argumentos.

Para definir una funcion se usa la palabra clave **def** seguida del nombre de la funcion y los argumentos que toma. El _bloque_ que sigue a esa definicion va a constituir el codigo que pertenece a esta (el "cuerpo" de la funcion).

In [29]:
def suma(a,b):  #aca definimos la funcion. El nombre de esta es "suma" y recibe dos argumentos, a y b
    c = a+b
    return c #con la palabra clave "return" especificamos que la funcion devuelve el valor c. 
    #cuando la ejecucion llega a "return", la ejecucion de la funcion termina.
 
print("hola!")
resultado = suma(2,3) #aca llamamos a la funcion suma que definimos mas arriba
print(resultado)


hola!
5


Una funcion cambia el orden de ejecucion normal del programa. En el ejemplo, se comienza ejecutando la linea 6.
Luego, al "llamar" a la funcion suma, se "salta" a la linea 1. las variables a y b adquieren los valores entregados a la funcion (en este caso, 2 y 3, respectivamente) y se ejecuta la linea 2. La linea 3 devuelve la ejecucion a la linea 7, y devuelve tambien el valor c (5, en este caso). Ahora la ejecucion sigue normalmente en la linea 8, donde el programa termina.


In [30]:
def Saludo(nombre):
    print("Hola",nombre) #esta funcion no contiene "return", por lo que no devuelve ningun valor
    #solamente "hace algo", en este caso, imprimir un saludo en pantalla
    
Saludo("Arthur") #La ejecucion salta a la linea 1, y la variable nombre adquiere el valor "Arthur".
Saludo("Ford")  #La ejecucion vuelve a saltar a la linea 1, y la variable nombre toma el valor "ford"
#notese que no hay ningun valor devuelto


Hola Arthur
Hola Ford


In [31]:
def Saludo():
    print("Hola") #esta funcion no contiene "return", por lo que no devuelve ningun valor
    #tampoco toma ningun argumento! Solamente lo mismo cada vez que se la llama. No es muy
    #util, pero se puede hacer.
    
Saludo()#La ejecucion salta a la linea 1.
Saludo()  #La ejecucion vuelve a saltar a la linea 1.

Hola
Hola


Las funciones que devuelven valores pueden devolver cualquier tipo de valor:
listas, tuplas, diccionarios,texto, etc. Una funcion puede devolver mas de un valor (tecnicamente, devuelve nua tupla de valores).

In [32]:
def sumamult(a,b):
    return a+b,a*b #devuelve dos valores (una tupla de dos valores)  


def make_list(a,b,c):
    return [a,b,c] #devuele una lista con los argumentos

suma,mult=sumamult(1,3) #asigna el primer elemento "devuelto" a "suma" y el segundo a "mult"
print(suma, mult)

lista=make_list(4,5,6)
print(lista)


4 3
[4, 5, 6]


Ademas de las funciones que nosotros podemos definir, Python contiene varias funciones pre-definidias, como parte del lenguaje (_built-in_). Vamos a ver algunas de ellas:


In [ ]:
milista=[1,2,3,4,5]

a=len(milista) #len devuelve el numero de elementos de la lista, tupla, texto que se le entregue
print(a)

a=len("un texto cualquiera") #en este caso, len devuelve el numero de caracteres en la cadena de texto
#incluyendo espacios en blanco
print(a)

a=abs(-2) #abs devuelve el valor absoluto del nombre que se le entregue
b=abs(2)
print(a,b)

b=round(2.2) #round devuelve el numero que se le entregue como argumento, pero redondeado a entero
print(b)

b=pow(3,2) #pow devuelve el primer numbero que se le entregue elevado al segundo
#en este caso, 3 al cuadrado

print(b)

#algunas funciones pre-definidas que ya habiamos visto son print y range

Un tipo especial de funciones son los _metodos_. Los metodos son funciones, pero van "unidas" a una variable. La variable a la que un metodo va unido se llama "receptor" del metodo. Vamos a ver algunos metodos que vienen unidos a distintos tipos de variables

 #### Metodos de cadenas de texto


In [33]:
#Toda variable de tipo texto tiene una serie de metodos definidos.

a="una cadena de texto"

#
# El metodo replace
#
b=a.replace("una","otra") #devuelve una nueva cadena de texto en la que se ha reemplazado todas las ocurrencias
#del primer argumento ("una" en este caso) por el segundo argumento ("otra")

print(b)

b=a.replace(" ","") #en este caso reemplazamos todos los espacios en blanco por nada. Es decir, sacamos los
#espacios

print(b)

numero_espanol="5,5"
numero_ingles=numero_espanol.replace(",",".")
print(numero_ingles)


otra cadena de texto
unacadenadetexto
5.5


In [34]:
#
# El metodo split 
#
a="una cadena de texto"

b=a.split() # "parte" la cadena en "trozos" y devuelve una lista de cadenas de texto, un elemento 
#por cada "trozo". Si no se le da ningun argumento "parte" la cadena en los espacios en blanco. 
print(b)

a="elemento1,elemento2,elemento3"
b=a.split(",") #pero podemos darle el separador que queramos
print(b)


['una', 'cadena', 'de', 'texto']
['elemento1', 'elemento2', 'elemento3']


In [35]:
#
# El metodo join
#
a=" "
b=["una","lista","de","palabras"]

c=a.join(b) # une una lista de cadenas de texto en una sola cadena, utilizando como separador la cadena inicial

print(c)

a="**"
c=a.join(b) #podemos usar el separador que queramos
print(c)

c=",".join(b) #no necesariamente tiene que estar en una variable tiene que estar en una variable

print(c)

una lista de palabras
una**lista**de**palabras
una,lista,de,palabras


In [3]:
#
# Los metodos startswith and endswith
#

#startswith devuelve True si la cadena de texto empieza con el texto dado como argumento a la funcion, 
#. Si no, devuelve False
a="una cadena de texto"

b=a.startswith("u")
c=a.startswith("U") #Python es sensible a mayusculas, es decir "A" es una letra distinta de "a"

print(b,c)

#endswith es similar, pero devuelve True si la cadena de texto _termina_ con el texto 
#dado como argumento a la funcion, Si no, devuelve False


b=a.endswith("o")
c=a.endswith("a")

print(b,c)


False True
False True


Existen varios otros metodo de cadenas de texto que pueden encontrar buscando en Internet.

#### Metodos de listas

Vamos a ver dos metodos de listas: **append** y **sort**. El primero es muy importante,
se usa con mucha frecuencia.



In [4]:
#
# El metodo append sirve para agregar valores a una lista
#

milista=[1,2,3,4,5,6]

milista.append(10)

lista2=[]

#vamos a agregar a lista2 solamente los valores de milista que sean pares

for i in milista:
    if i%2!=0:
        continue
    lista2.append(i)

print(lista2)

[2, 4, 6, 10]


In [8]:
#
# el metodo sort ordena una lista en forma ascendente. Si la lista contiene cadenas de texto, estas quedan
# en orden alfabetico
#

l=[3,8,2,0,-1,40,45]
l.sort() #sort no devuelve una nueva lista, sino que modifica la lista original
print(l)

l2=["Clara","Andres","Amanda","Berta"]
l2.sort()
print(l2)

#Es posible entregar un argumento a sort para que ordene la lista en orden descendente

l.sort(reverse=True)
print(l)
l2.sort(reverse=True)
print(l2)

[-1, 0, 2, 3, 8, 40, 45]
['Amanda', 'Andres', 'Berta', 'Clara']
[45, 40, 8, 3, 2, 0, -1]
['Clara', 'Berta', 'Andres', 'Amanda']


In [9]:
l3=[3,8,2,0,-1,"Amanda","Berta"]

l3.sort() #error! la lista tiene que contener solamente elementos numericos, o solamente cadenas de texto


TypeError: '<' not supported between instances of 'str' and 'int'

## La libreria estandar

Ademas de las funciones que vienen en el lenguaje (_build in_) Python dispone de una libreria estandar que podemos llamar, y que nos entrega una gran cantidad de funciones utiles. Aca vamos a ver solamente algunos pocos ejemplos.

Para usar una parte de la libreria estandar tenemos que "importarla"

Veamos primero la libreria math, que tiene funciones y variables pre-definidas

In [11]:
import math #importamos la libreria math, parte de la libreria estandar de Python

print(math.pi) # math.pi indica la variable pi, que es parte de la libreria math. 

a = math.cos(math.pi/2) # math.cos es la funcion cos, parte de la libreria math. devuelve el coseno
#de lo que le entreguemos como argumento (math.cos asume que el argumento esta en radiantes)

print(a)

print(math.e) #math.e es e, el numero de Euler, la base del logaritmo natural

print(math.log(math.e)) #math.log devuelve el logaritmo natural de lo que se le de como argumento

3.141592653589793
6.123233995736766e-17
2.718281828459045
1.0


In [12]:
import sys #sys es otra libreria muy importante. Nos permite leer input del usuario

#la variable mas importante de sys es sys.argv

#sys.argv es una lista. Su primer elemento, sys.argv[0] es el nombre con el que se 
#"llamo" a nuestro programa. Su segundo elemento, sys.argv[1] 
#es el primer parametro entregado por el usuario al llamar al programa, su tercer elemento, sys.argv[2]
#es el segundo parametro entregado por el usuario, y asi sucesivamente. Todos los parametros que el
#usuario entregue quedan registrados como _cadenas de texto_ en sys.argv

#por ejemplo, si nuestro programa se llama "filter.py" y el usuario lo llama con el siguiente comando:

# ./filter.py archivo1.txt archivo2.txt 

#sys.argv va a valer: ["./filter.py","archivo1.txt","archivo2.txt"]

#sys.argv es la mejor manera de obtener informacion del usuario, y la unica que vamos a ver aqui.

print(sys.argv) #en este caso, sys.argv contiene la informacion que use Jupyter ejecutar nuestro codigo 


['/usr/lib/python3.10/site-packages/ipykernel_launcher.py', '-f', '/home/rmera/.local/share/jupyter/runtime/kernel-41a3e023-a160-4e2b-968a-ef87b19703e9.json']


In [22]:
import os #os contiene funciones y variables para acceder al sistema operativo

print(os.getcwd()) #os.getcwd es una funcion que devuelve una cadena de texto con el directorio/carpeta actual.



/wrk/PythonTeaching/TEST


In [23]:
original=os.getcwd()



os.chdir("TEST") #cambia el directorio actual a TEST

print(os.getcwd()) #ahora nuestro directorio actual es TEST, dentro de nuestro directorio anterior

os.chdir(original) #volvemos a nuestro directorio original

print(os.getcwd())

/wrk/PythonTeaching/TEST
/wrk/PythonTeaching


## Leyendo archivos

Vamos a ver como leer archivos en Python. Tambien es posible escribir texto en archivos, pero, ademas de ser facil, rara vez es necesario (en Unix). Generalmente es preferible escribir en la salida estandar (monitor) y dejar que el usuario redirija el texto a un archivo si lo cree necesario.

Para leer un archivo, este debe abrirse con la funcion **open**, una de las funciones que son parte del lenguaje, como **len**, **abs**, etc.


In [26]:
handle = open("nombres.dat","r") #el primer argumento de open es el nombre del archivo, el segundo "r"
#significa que lo estamos abriendo para leerlo ("reading") no para escribir en el.

#open devuelve una representacion del archivo que tiene varios metodos que podemos usar para extraer informacion

primera=handle.readline() #este metodo nos devuelve una linea del archivo cada vez que lo llamamos. La primera
#llamada nos devuelve la primera linea del archivo, la segunda, la segunda linea, y asi.

print("primera linea:", primera)

#lo siguiente nos permite iterar por las lineas del archivo como si fuera una lista o tupla.
# en cada vuelta, se le asigna una linea del archivo a i. Notese que las lineas previamente
#leidas no se incluyen
for i in handle:
    print(i)
    
handle.close() #cerramos el archivo

primera linea: spam, eggs and bacon

spam, bacon and spam

spam, spam, spam, eggs, bacon and spam



## Temas especializados

### Formateando cadenas de texto

Digamos que queremos una cadena de textos que incluye numeros. Como podriamos hacerlo?

Una forma es simplemente transformar los numeros en cadenas de texto con la funcion **str** y juntar esa cadena con el resto

In [3]:
a="mi cadena de texto"
num=1.456988888888888888

b=a+" "+str(num)

print(b)

mi cadena de texto 1.4569888888888889


El problema con esa solucion, es que el numero no tiene _formato_ 


En Python podemos crear cadenas de texto que incluyan numeros con formato. De hecho, hay dos formas distintas de lograr esto. En este tutorial veremos la forma "antigua", que la mayoria de los programadores en Python no prefiere. Yo estoy entre la minoria que _si_ prefiere esta forma, principalmente porque es el mismo metodo utilizado en otros lenguajes de programacion. 

Vamos a crear la misma cadena anterior pero asegurandonos de incluir solo 4 cifras despues del punto decimal.


In [5]:
num=1.456988888888888888
a="mi cadena de texto %6.4f"%(num)

print(a)

mi cadena de texto 1.4570


La parte importante es "\%6.4f" En una cadena de texto, el simbolo "%" indica que vamos a insertar el valor de una variable en ese lugar. La letra "f" al final, nos indica que la variable es un **float**. 6.4 indica que el numero va a ocupar 6 espacios en total (incluyendo el punto decimal) y que vamos a usar 4 cifras despues del punto decimal.

Al final de la cadena de texto, insertamos otro "%" seguido de una tupla, que contiene los valores que vamos a insertar en la cadena de texto, en el mismo orden en el que aparecen en la cadena.

Podemos asignarle mas espacio a nuestro numero. Si el numero no es lo suficientemente grande para llenar el espacio que le asignemos, los demas espacios se llenan con espacios en blanco.

In [7]:
num=1.456988888888888888
a="Un numero: %9.4f"%(num) #si usamos solo 4 decimales, num no alcanza a ocupar 9 espacios
#por lo que se agregan espacios en blanco
print(a)

Un numero:    1.4570


A veces podemos querer que los espacios que el numero no ocupe se rellenen con 0, no con espacios en blanco. 
Eso es facil de hacer, solo hay que agregar un 0 entre "\%" y el primer numero (9, en este caso)

In [8]:
num=1.456988888888888888
a="Un numero: %09.4f"%(num) #Todo igual que antes, salvo por el 0 depsues del %

print(a)

Un numero: 0001.4570


Si queremos imprimir un numero entero, es mas facil todavia. En vez de "f" se usa "d", y no se agrega el punto 
ni el numero de cifras despues del punto decimal

In [11]:
entero=89

a="Un numero: %2d"%(entero)

print(a)

b="El mismo numero, con mas espacios: %4d"%(entero)

print(b)

c="Igual que lo anterior, pero completando con ceros %04d"%(entero)

print(c)

Un numero: 89
El mismo numero, con mas espacios:   89
Igual que lo anterior, pero completando con ceros 0089


In [ ]:
Podemos tambien agregar variables que sean cadenas de texto. Si queremos, podemos especificar el 
espacio que vamos a asignarles



In [12]:
saludo="Hola"

a="El saludo es: %s"%(saludo)
print(a)

b="El saludo es: %6s"%(saludo) #aca dejamos mas espacio para la cadena
print(b)





El saludo es: Hola
El saludo es   Hola


En todos los ejemplos anteriores, el valor que vamos a insertar se _alinea_ hacia la derecha 
(es decir, si sobra espacio, se insertan espacios en blanco a la izquierda del valor). Podemos cambiar este 
comportamiento alineando a la izquierda agregando un signo "-" despues del "%"

In [16]:
b="El saludo es: **%6s**"%(saludo) #Alineando a la derecha
print(b)
b="El saludo es: **%-6s**"%(saludo) #A la izquierda
print(b)

#Tambien funciona con numeros

entero=89

b="Numero con espacios espacios: ***%4d***"%(entero)

print(b)

c="Numero con espacios ***%-4d***"%(entero)

print(c)

#Y con decimales

num=1.456988888888888888
a="Un numero: ***%9.4f***"%(num) 
print(a)
a="Un numero: ***%-9.4f***"%(num) 
print(a)


El saludo es: **  Hola**
El saludo es: **Hola  **
Numero con espacios espacios: ***  89***
Numero con espacios ***89  ***
Un numero: ***   1.4570***
Un numero: ***1.4570   ***


In [18]:
##Ahora probemos combinando todo, insertando varias variables en nuestro texto

entero=89
decimal=7.4598777777
texto="Hola!"

a="%s Ud. tiene %2d monedas, cada una por una valor de %06.2f pesos"%(texto,entero,decimal)

print(a)

# Por supuesto podemos tambien imprimir directamente nuestra cadena de texto, sin ponerla 
# en una variable

print("%s Ud. tiene %2d monedas, cada una por una valor de %6.2f pesos"%(texto,entero,decimal))



Hola! Ud. tiene 89 monedas, cada una por una valor de 007.46 pesos
Hola! Ud. tiene 89 monedas, cada una por una valor de   7.46 pesos


Una ultima cosa, que ocurre si queremos incluir el signo "%" en nuestra cadena de texto?
como hacemos para que se interprete como literalmente ese signo, y no que vamos a insertar
un valor?

Simplemente, ponemos el "%" dos veces. Va a aparecer una vez en la cadena de texto


In [21]:
dec=5.678

a="Un %3.1f%% de los intentos, fracasa"%(dec)
print(a)

nombre="Nadie"
print("%s tiene 0%% de probabilidades de lograrlo"%(nombre))

Un 5.7% de los intentos, fracasa
Nadie tiene 0% de probabilidades de lograrlo


### Numpy

Numpy es la principal libreria de matematicas en Python. O, al menos, la mas "fundamental" en el sentido de que casi todas las otras depende de ella.

Numpy define un nuevo tipo, el _array_. Un _array_ representa a un vector o una matriz (o una "hiper-matriz" de N dimensiones). El _array_ es similar a una lista de listas, con algunas diferencias.

- Un _array_ no es inmutable, en el sentido de que sus elementos se pueden modificar, pero el numero de 
elementos totales del array es fijo

- Un _array_ solamente contiene numeros (en coma flotante)

Un array contiene una serie de metodos utiles.



In [25]:
import numpy as np #necesitamos importar la libreria numpy para poder usarla. Todas las funciones de numpy
#van a comenzar con "np."

listadelistas=[[1,2,3],[4,5,6],[7,8,9]]

matrix=np.array(listadelistas) #creamos un array de numpy a partir de una lista de listas con la funcion np.array

print(matrix)

print(matrix.max()) #el elemento de mayor valor en la matriz
print(matrix.mean(),matrix.std()) #la media (promedio) de los elementos de la matrix, y su desviacion estandar

m2=matrix*10 #cada elemento se multiplica por 10. Mucho mas rapido que usar un "for"

print(m2)

vector=np.array([10,11,12])

print(matrix*m2) #esta es la multiplicacion elemento por elemento, no la multiplicacion matricial

v2=np.dot(vector,matrix) #np.dot es la multiplicacion matricial.
print(v2)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
5.0 2.581988897471611
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]
[138 171 204]


### Variables y _referencias (tema avanzado)

Una variable es una "cajita" que contiene un valor. Por ejemplo,  si hacemos

```
a = 12
```

a es una variable que contiene el valor 12. El valor 12 se guarda en algun sector de la memoria de nuestro computador (ese sector tiene asociado un numero o _direccion_) y se asocia a esa variable.

Sin embargo, algunas variables no contienen un valor _per se_, sino que contienen _la direccion en la memoria_ de un valor, o una _referencia_ a una valor. Este es el caso de las listas. 



In [27]:
l1=[1,2,3]

l2=[4,5,6,l1]

print(l2) #l2 es una lista que contiene a la lista l1

l2[3][2]=99

print("Esto es esperable:", l2) #esto es totalmente esperable


#puesto que l2 no contiene una copia de los valores de l1, sino que contiene la direccion en la memoria de l1, 
#si modificamos a l1 dentro de l2, estamos modificando lo que hay en esa direccion en la memoria (l1), por lo 
#que el cambio tambien se ve en l1
print("Esto no es tan esperable!:", l1)



[4, 5, 6, [1, 2, 3]]
Esto es esperable: [4, 5, 6, [1, 2, 99]]
Esto no es tan esperable!: [1, 2, 99]


In [ ]:
l1=[1,2,3]

l2=[4,5,6,l1]

print(l2) #l2 es una lista que contiene a la lista l1

l1[0]=99

print("Esto es esperable:", l1) d


#Tambien funciona al reves! si modificamos l1, l2 tambien se modifica
#porque no tiene una copia de los valores de l1, sino la direccion en la memoria de esa variable. Si lo que
#hay en esa direccion (l1) se modifica, el cambio tambien se refleja en l2
print("Esto no es tan esperable!:", l2)



In [30]:
a=1
l=[a,2,3]
print(l)
l[0]=10

print(l)

#por que en este caso a no se modifica? Es porque, como vimos antes
#los numeros, los booleanos, las tuplas y las cadenas de texto son
#inmutables. No se pueden modificar. Entonces, al modificar l[0] no
#modificamos a, sino que asignamos otra nueva variable a l[0]
print("aca a no se modifica!:",a)



[1, 2, 3]
[10, 2, 3]
aca a no se modifica!: 1


In [31]:
a=1
l=[a,2,3]
print(l)
a=200
print(a)

#al reves pasa lo mismo. Como a es inmutable, si la cambiamos, no estamos cambiando la variable a
#estamos creando una nueva y asignandole el nombre "a", mientras que la lista l sigue conteniendo la
#referencia a la variable antigua.

print("l no se modifica:",l)

[1, 2, 3]
200
l no se modifica: [1, 2, 3]


Esto es un poco complejo, pero, la moraleja es, cuidado con las listas de listas, o listas de diccionarios.